import { voice } from './mapping.ts';
import type { XgSfxVoice } from './mapping.ts';

export const XG_SFX_VOICES: readonly XgSfxVoice[] = [
  { program: 0, name: 'Cutting Noise', from: voice(1, 120) },
  { program: 1, name: 'Cutting Noise 2', from: voice(1, 120) },
  { program: 3, name: 'String Slap', from: voice(2, 120) },
  { program: 16, name: 'Flute Key Click', from: voice(1, 121) },
  { program: 32, name: 'Rain', from: voice(1, 122) },
  { program: 33, name: 'Thunder', from: voice(2, 122) },
  { program: 34, name: 'Wind', from: voice(3, 122) },
  { program: 35, name: 'Stream', from: voice(4, 122) },
  { program: 36, name: 'Bubble', from: voice(5, 122) },
  { program: 37, name: 'Feed', from: null, reason: 'no-substitute' },
  { program: 48, name: 'Dog', from: voice(1, 123) },
  { program: 49, name: 'Horse Gallop', from: voice(2, 123) },
  { program: 50, name: 'Bird 2', from: voice(3, 123) },
  { program: 54, name: 'Ghost', from: null, reason: 'no-substitute' },
  { program: 55, name: 'Maou', from: null, reason: 'no-substitute' },
  { program: 64, name: 'Telephone Dial', from: voice(0, 124) },
  { program: 65, name: 'Door Squeak', from: voice(2, 124) },
  { program: 66, name: 'Door Slam', from: voice(3, 124) },
  { program: 67, name: 'Scratch', from: voice(4, 124) },
  { program: 68, name: 'Scratch 2', from: voice(4, 124) },
  { program: 69, name: 'Wind Chime', from: voice(5, 124) },
  { program: 70, name: 'Telephone Ring 2', from: voice(1, 124) },
  { program: 80, name: 'Car Engine', from: voice(1, 125) },
  { program: 81, name: 'Car Stop', from: voice(2, 125) },
  { program: 82, name: 'Car Pass', from: voice(3, 125) },
  { program: 83, name: 'Car Crash', from: voice(4, 125) },
  { program: 84, name: 'Siren', from: voice(5, 125) },
  { program: 85, name: 'Train', from: voice(6, 125) },
  { program: 86, name: 'Jetplane', from: voice(7, 125) },
  { program: 87, name: 'Starship', from: voice(8, 125) },
  { program: 88, name: 'Burst', from: voice(9, 125) },
  { program: 89, name: 'Coaster', from: null, reason: 'no-substitute' },
  { program: 90, name: 'Submarine', from: null, reason: 'no-substitute' },
  { program: 96, name: 'Laughing', from: voice(1, 126) },
  { program: 97, name: 'Scream', from: voice(2, 126) },
  { program: 98, name: 'Punch', from: voice(3, 126) },
  { program: 99, name: 'Heartbeat', from: voice(4, 126) },
  { program: 100, name: 'Footsteps', from: voice(5, 126) },
  { program: 112, name: 'Machine Gun', from: voice(1, 127) },
  { program: 113, name: 'Laser Gun', from: voice(2, 127) },
  { program: 114, name: 'Explosion', from: voice(3, 127) },
  { program: 115, name: 'Firework', from: voice(3, 127) },
];
